/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Herman 4144
 */
public class obat extends javax.swing.JFrame {
    Connection conn;
   Statement stmt;
   
   
   koneksi kon;
   DefaultTableModel tabmode;

    /**
     * Creates new form obat
     */
    public obat() {
        initComponents();
        Connect();
        LoadobatID();
   
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void Connect(){
       try {
           Class.forName("com.mysql.jdbc.Driver");
           try {
               con = DriverManager.getConnection("jdbc:mysql://localhost/apotik", "root", "");
           } catch (SQLException ex) {
               Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
           }
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
    
    
    public void LoadobatID(){
           try {
               pst = con.prepareStatement("select id from menu_obat");
               rs = pst.executeQuery();
               
               
               jComboBox1.removeAllItems();
               
               while(rs.next()){
                   jComboBox1.addItem(rs.getString(1).toString());
               }
               
               
           } catch (SQLException ex) {
               Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnama_obat = new javax.swing.JTextField();
        txtkatagori = new javax.swing.JTextField();
        txtkode_obat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("OBAT");

        jLabel3.setText("id");

        jLabel4.setText("nama_obat");

        jLabel5.setText("katagori");

        jLabel6.setText("kode_obat");

        txtnama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_obatActionPerformed(evt);
            }
        });

        txtkatagori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkatagoriActionPerformed(evt);
            }
        });

        txtkode_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_obatActionPerformed(evt);
            }
        });

        jButton1.setText("baru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("delate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("view");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtkode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkatagori, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkatagori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_obatActionPerformed

    private void txtkatagoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkatagoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkatagoriActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        try {
           String id = jComboBox1.getSelectedItem().toString();
           
           pst = con.prepareStatement("select * from menu_obat where id=?");
           pst.setString(1, id);
           rs = pst.executeQuery();
           
           if (rs.next()==true){
               txtnama_obat.setText(rs.getString(2));
               txtkatagori.setText(rs.getString(3));
               txtkode_obat.setText(rs.getString(4));
           }
           
       } catch (SQLException ex) {
           Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtkode_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkode_obatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        try {
            String nama_obat = txtnama_obat.getText();
            String katagori = txtkatagori.getText();
            String kode_obat = txtkode_obat.getText();
            
            pst = con.prepareStatement("insert into menu_obat (nama_obat, katagori, kode_obat)values (?,?,?)");
             pst.setString(1, nama_obat);
               pst.setString(2, katagori);
               pst.setString(3, kode_obat);
          
               
               int k = pst.executeUpdate();
               
               if (k==1){
                   JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                   txtnama_obat.setText("");
                   txtkatagori.setText("");
                   txtkode_obat.setText("");
                   txtnama_obat.requestFocus();
               }
               
               else{
                    JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan");
               }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                   txtnama_obat.setText("");
                   txtkatagori.setText("");
                   txtkode_obat.setText("");
                   txtnama_obat.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        String id = jComboBox1.getSelectedItem().toString();
       try {  
               String nama_obat = txtnama_obat.getText();
               String katagori = txtkatagori.getText();
               String kode_obat = txtkode_obat.getText();
           
           pst = con.prepareStatement("update menu_obat set nama_obat=?, katagori=?, kode_obat=? where id=?");
            pst.setString(1, nama_obat);
               pst.setString(2, katagori);
               pst.setString(3, kode_obat);
               pst.setString(4, id);
               
               int k = pst.executeUpdate();
               
               if (k==1){
                   JOptionPane.showMessageDialog(this, "Data Berhasil Di Update");
                   txtnama_obat.setText("");
                   txtkatagori.setText("");
                   txtkode_obat.setText("");
                   txtnama_obat.requestFocus();
                   LoadobatID();
               
               }
               
               else{
                    JOptionPane.showMessageDialog(this, "Data Gagal Di Update");
               }

           
           
       } catch (SQLException ex) {
           Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   
        try {  
           String id = jComboBox1.getSelectedItem().toString();
              
           pst = con.prepareStatement("delete from menu_obat where id=?");
            
             pst.setString(1, id);
               
               int k = pst.executeUpdate();
               
               if (k==1){
                   JOptionPane.showMessageDialog(this, "Data Berhasil Di Hapus");
                 txtnama_obat.setText("");
                   txtkatagori.setText("");
                   txtkode_obat.setText("");
                   txtnama_obat.requestFocus();
                   LoadobatID();
               
               }
               
               else{
                    JOptionPane.showMessageDialog(this, "Data Gagal Di Hapus");
               }

           
           
       } catch (SQLException ex) {
           Logger.getLogger(obat.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtkatagori;
    private javax.swing.JTextField txtkode_obat;
    private javax.swing.JTextField txtnama_obat;
    // End of variables declaration//GEN-END:variables
}
